### ISSUE TITLE
Install system packages before pip packages

### ISSUE THREAD

**Issue by christian-safka** [replicate/setup-cog#11]
```     
      - name: Setup Cog
          uses: replicate/setup-cog@v1.0.2
          with:
             cog-version: v0.9.0-beta6

      - name: 'Build Container Image'
         run: |
          cog build -t model-name:latest --tag ghcr.io/namespace/model-name:latest
```

One pip package requires cmake to be installed but it seems that system packages don't finish installing before the pip install.  This builds fine locally.  This should be replicable by adding cmake in system packages and "dlib" in pip packages.

Any way to make those system/pip installs run synchronously after each other?
