### ISSUE TITLE
failed with the following error

### ISSUE THREAD

**Issue by sky-admin** [replicate/setup-cog#34]
![image](https://github.com/replicate/setup-cog/assets/6292668/e9aa6cbd-0f15-4916-8838-1898f58f767e)

**Comment by zeke** [comment]
This is fixed in newer versions of setup-cog. 


Try this:

```yml
- name: Setup Cog
  uses: replicate/setup-cog@v2
  with:
    token: ${{ secrets.REPLICATE_API_TOKEN }}

- name: Download weights
  run: cog run script/download-weights

- name: Push to Replicate
  run: cog push r8.im/zeke/hello-world
```

Closing this issue, but please let us know if the problem persists.
