### ISSUE TITLE
Document how to get more disk space

### ISSUE THREAD

**Issue by zeke** [replicate/setup-cog#38]
Sometimes workflows fail because the environment runs out of disk space. Let's update the docs and examples with advice on how to work around this.

## Use an Action to delete stuff

```
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4
```

## Use a bigger hosted runner

https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#machine-sizes-for-larger-runners
